language: java
jdk:
  - oraclejdk8
  - oraclejdk9
services:
  - redis-server
after_success:
  - mvn cobertura:cobertura coveralls:report

before_install:
  - wget https://github.com/gresrun/jesque/archive/53fcb490c5c9cde81cdac9abb3c8365cf0181a6d.zip
  - unzip 53fcb490c5c9cde81cdac9abb3c8365cf0181a6d.zip
  - cp -rT jesque-53fcb490c5c9cde81cdac9abb3c8365cf0181a6d ./
  - rm -r jesque-53fcb490c5c9cde81cdac9abb3c8365cf0181a6d
  - rm 53fcb490c5c9cde81cdac9abb3c8365cf0181a6d.zip
